version: "3"
services:
  app:
    container_name: docker-node
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
